# See: https://gohugo.io/getting-started/configuration/

####### BASE CONFIG #######
  baseURL = "https://kolverse.youronly.one/"                                              # .Site.BaseURL
  title = "Kolverse Worldbuilding & Writing Project"                                                # .Site.Title; IMPT for Schema.org; OpenGraph; Twitter Cards; RDFa, Microdata, JSON-LD
  copyright = ""                                            # .Site.Copyright; leave empty to override theme
  timeZone = "Etc/UTC"


####### FRONTEND #######
  paginate = 10                                             # default: 10
  rssLimit = 25                                             # default: -1
  summaryLength = 240                                        # default: 70
  titleCaseStyle = "firstupper"                                     # default: AP; our choice: firstupper; backup: Chicago


####### LANGUAGE #######
  languageCode = "en-ph"
  defaultContentLanguage = "en-ph"                             # default: en
  #defaultContentLanguageInSubdir = false                   # default: false
  hasCJKLanguage = true                                    # default: false
  # Our LANG: 'en', 'en-ph', 'fil', 'phi-hang', 'tl-tglg', 'zh-hant', 'zh-hans', 'zh-bopo', 'ja', 'ko'
  disableLanguages = ['en', 'fil', 'phi-hang', 'tl-tglg', 'zh-hant', 'zh-hans', 'zh-bopo', 'ja', 'ko']



####### BACKEND #######
  disableKinds = ["robotsTXT"]
  #enableGitInfo = false                                     # default: false; for Git versioning
  enableMissingTranslationPlaceholders = true              # default: false
  #pluralizeListTitles = false                                # default: true
  #publishDir = "public"                                     # default: public
  #timeout = "30s"                                           # default: 30s

  #### Other settings ####

  ## Theme settings ##
  ## Theme settings ##


#######  #######  #######  #######  #######  #######  #######  #######
