# See: https://gohugo.io/content-management/image-processing/#imaging-configuration

anchor = "Smart"                                  # default: Smart
bgColor = "#ffffff"                               # default: #ffffff; if transparency is not supported
hint = "photo"                                    # default: photo; WebP
quality = 75                                      # default: 75; JPEG and WebP
resampleFilter = "MitchellNetravali"              # default: Box

[exif]
  disableDate = false                             # default: false
  disableLatLong = false                          # default: false
  excludeFields = ""                              # default: ""; performance and cache size
  includeFields = ""                              # default: ""; performance and cache size
  #includeFields = "Artist|LensModel|FNumber|ExposureTime"
