# See: https://gohugo.io/templates/output-formats/#media-types

# https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types
