replacements = [
  "gitlab.com/yelosan/hugo-semantic-web -> /home/yuki/repos/yelosan/hugo-semantic-web",
  "gitlab.com/yelosan/hugo-shortcodes -> /home/yuki/repos/yelosan/hugo-shortcodes",
  "gitlab.com/yelosan/hugo-feeds -> /home/yuki/repos/yelosan/hugo-feeds",
  "github.com/techmagus/maupassant-hugo -> /home/yuki/repos/hugo-themes/kolverse-maupassant-hugo"
]

[hugoVersion]
  extended = true
  #max = ""
  min = "0.105.0"

[[imports]]
  disable = false                           # default: false
  ignoreConfig = false                      # default: false
  ignoreImports = false                     # default: false
  noMounts = false                          # default: false
  noVendor = false                          # default: false
  path = "gitlab.com/yelosan/hugo-semantic-web"

[[imports]]
  path = "gitlab.com/yelosan/hugo-shortcodes"

[[imports]]
  path = "gitlab.com/yelosan/hugo-feeds"

[[imports]]
  path = "github.com/techmagus/maupassant-hugo"

# BGN: // content
#[[imports]]
#  path = "github.com/kolverse/{REPO_NAME}"
#    [[imports.mounts]]
#      source = "{REPO_NAME}/en"
#      target = "content"
#      lang = "en"
# END: // content


#[[imports]]
#  path = "gitlab.com/youronlyone/images"
#  # BGN: /techmagus/ images
#    [[imports.mounts]]
#      source = "techmagus"
#      target = "assets/images"
#  # END: /techmagus/ images


# See: https://gohugo.io/hugo-modules/configuration/#module-config-mounts
#   if you add a mounts section you should remove the old staticDir etc. settings.
#   When you add a mount, the default mount for the concerned target root is ignored: be sure to explicitly add it.
  [[mounts]]
    source = "archetypes"
    target = "archetypes"

  [[mounts]]
    source = "assets"
    target = "assets"

  [[mounts]]
    source = "content/en"
    target = "content"
    lang = "en"                                        # when in multihost / multilang mode
  #[[mounts]]
  #  source = "content/en-ph"
  #  target = "content"
  #  lang = "en-ph"                                      # when in multihost / multilang mode
  #[[mounts]]
  #  source = "content/ja"
  #  target = "content"
  #  lang = "ja"                                         # when in multihost / multilang mode
  #[[mounts]]
  #  source = "content/ko"
  #  target = "content"
  #  lang = "ko"                                         # when in multihost / multilang mode

  [[mounts]]
    source = "data"
    target = "data"

  [[mounts]]
    source = "i18n"
    target = "i18n"

  [[mounts]]
    source = "layouts"
    target = "layouts"

  [[mounts]]
    source = "static/en"
    target = "static"
    lang = "en"                                        # when in multihost / multilang mode
  #[[mounts]]
  #  source = "static/en-ph"
  #  target = "static"
  #  lang = "en-ph"                                      # when in multihost / multilang mode
  #[[mounts]]
  #  source = "static/ja"
  #  target = "static"
  #  lang = "ja"                                         # when in multihost / multilang mode
  #[[mounts]]
  #  source = "static/ko"
  #  target = "static"
  #  lang = "ko"                                         # when in multihost / multilang mode
