# See: https://gohugo.io/templates/output-formats/#output-formats-for-pages

# home/atom.xml
home = ["HTML", "JSON", "Atom", "RSS"]          # default: HTML, RSS

# home/section/PAGE-POST/atom.xml
page = ["HTML", "JSON", "Atom", "RSS"]                                 # default: HTML

# home/SECTION/atom.xml
section = ["HTML", "JSON", "Atom", "RSS"]               # default: HTML, RSS

# home/TAXONOMY/atom.xml
taxonomy = ["HTML", "JSON", "Atom", "RSS"]              # default: HTML, RSS

# home/taxonomy/TERM/atom.xml
term = ["HTML", "JSON", "Atom", "RSS"]                  # default: HTML, RSS

# rss
rss = ["Atom", "RSS"]                                           # default: RSS
