# See: https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes

#mainSections = ['blog', 'posts']                          # Hugo default
mainTypes = ['article', 'sitepage', 'review']             # Yelosan default

# See: https://gohugo.io/content-management/mathematics/
math = false                                              # Should always be false.

devnotes = false

# Usually: fonts.bunny.net; fonts.googleapis.com; fonts.gstatic.com; cdn.jsdelivr.net
preconnect = ['https://fonts.googleapis.com', 'https://fonts.gstatic.com', 'https://cdn.jsdelivr.net']

# Usually: unpkg.com; cdnjs.cloudflare.com; ajax.cloudflare.com
dnsprefetch = ['https://cdnjs.cloudflare.com', 'https://ajax.cloudflare.com']

#favicon_mstilecolor = ''                           # per site
metarobots = 'index'
#relcanonical = ''                                  # per site

## BGN: old, replace this
  rssfull = true
  jquerycdn = false
## END: old, replace this

### BGN: Structured Data ###
  siteStartYear = 2017

  #copyright = 'Copyleft 🄯 2024 Yelosan Publishing, YourOnly.One; under a Creative Commons-Attribution-ShareAlike (CC-By-SA) 4.0 International License.'
  description = 'A Creative Commons-Attribution-ShareAlike 4.0 Collaborative and Shared Worldbuilding and Writing Project.'
  license = 'https://creativecommons.org/licenses/by-sa/4.0/'
  keywords = ['KWWP', 'Kolverse', 'Collaborative World', 'Collaborative Universe', 'Shared World', 'Shared Universe', 'Worldbuilding', 'Writing Project']                              # Can be overriden per page
  #images = ['', '']
### END: Structured Data ###

### BGN: Theme settings
  subtitle = "Build a beautiful and simple website in minutes"
  #mainSections = ["post","posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  #favicon = "img/favicon.ico"
  #dateFormat = "January 2, 2006"
  #commit = false
  #rss = true
  #comments = true
  #readingTime = true
  #wordCount = true
  #useHLJS = true
  socialShare = true
  #delayDisqus = true
  showRelatedPosts = true
  #hideAuthor = true
  #gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
  #disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

  #[[bigimg]]
  #  src = "img/triangle.jpg"
  #  desc = "Triangle"
  #[[bigimg]]
  #  src = "img/sphere.jpg"
  #  desc = "Sphere"
  #  # position: see values of CSS background-position.
  #  position = "center top"
  #[[bigimg]]
  #  src = "img/hexagon.jpg"
  #  desc = "Hexagon"

  #[Author]
  #  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  #  name = "Some Person"
  #  website = "yourwebsite.com"
  #  email = "youremail@domain.com"
  #  facebook = "username"
  #  github = "username"
  #  gitlab = "username"
  #  bitbucket = "username"
  #  twitter = "username"
  #  reddit = "username"
  #  linkedin = "username"
  #  xing = "username"
  #  stackoverflow = "users/XXXXXXX/username"
  #  snapchat = "username"
  #  instagram = "username"
  #  youtube = "user/username" # or channel/channelname
  #  soundcloud = "username"
  #  spotify = "username"
  #  bandcamp = "username"
  #  itchio = "username"
  #  vk = "username"
  #  paypal = "username"
  #  telegram = "username"
  #  500px = "username"
  #  codepen = "username"
  #  mastodon = "url"
  #  kaggle = "username"
  #  weibo = "username"
  #  slack = "username"
  #  medium = "username"
  #  discord = "invite code (https://discord.gg/XXXXXXX)"
  #  strava = "userid"

### END: Theme settings

### BGN: Hugo module settings ###
  ##### BGN: syndication #####
    ## Custom entries only work if placed in per-site params.toml ##
    [[sns]]
      url = 'is.youronly.one'
      icon = 'bluesky.svg'
    [[sns]]
      url = 't.youronly.one'
      icon = 'tumblr.svg'

    ## Defaults
    [[sns]]
      url = 'blogspot.com'
      icon = 'blogspot.svg'
    [[sns]]
      url = 'bsky.app'
      icon = 'bluesky.svg'
    [[sns]]
      url = 'c.im'
      icon = 'mastodon.png'
    [[sns]]
      url = 'c.wtf'
      icon = 'rebased.svg'
    [[sns]]
      url = 'catodon.social'
      icon = 'catodon.png'
    [[sns]]
      url = 'coracle.social'
      icon = 'nostr.svg'
    [[sns]]
      url = 'diasp.org'
      icon = 'diaspora.svg'
    [[sns]]
      url = 'ebin.club'
      icon = 'fediverse.svg'
    [[sns]]
      url = 'facebook.com'
      icon = 'facebook.svg'
    [[sns]]
      url = 'fb.com'
      icon = 'facebook.svg'
    [[sns]]
      url = 'fedia.io'
      icon = 'mbin.svg'
    [[sns]]
      url = 'fedia.social'
      icon = 'iceshrimp.png'
    [[sns]]
      url = 'instagram.com'
      icon = 'instagram.svg'
    [[sns]]
      url = 'iris.to'
      icon = 'nostr.svg'
    [[sns]]
      url = 'mastodon.online'
      icon = 'mastodon.png'
    [[sns]]
      url = 'mastodon.social'
      icon = 'mastodon.png'
    [[sns]]
      url = 'naver.com'
      icon = 'naver.png'
    [[sns]]
      url = 'njump.me'
      icon = 'nostr.svg'
    [[sns]]
      url = 'nosta.me'
      icon = 'nostr.svg'
    [[sns]]
      url = 'p.lu'
      icon = 'peertube.svg'
    [[sns]]
      url = 'pixelfed.social'
      icon = 'pixelfed.svg'
    [[sns]]
      url = 'plurk.com'
      icon = 'plurk.svg'
    [[sns]]
      url = 'primal.net'
      icon = 'nostr.svg'
    [[sns]]
      url = 'reddit.com'
      icon = 'reddit.svg'
    [[sns]]
      url = 'satellite.earth'
      icon = 'nostr.svg'
    [[sns]]
      url = 'snort.social'
      icon = 'nostr.svg'
    [[sns]]
      url = 'socialhome.network'
      icon = 'socialhome-black.svg'
    [[sns]]
      url = 'spoutible.com'
      icon = 'spoutible.png'
    [[sns]]
      url = 'threads.net'
      icon = 'threads.svg'
    [[sns]]
      url = 'tumblr.com'
      icon = 'tumblr.svg'
    [[sns]]
      url = 'twitter.com'
      icon = 'twitter.svg'
    [[sns]]
      url = 'wordpress.com'
      icon = 'wordpress.svg'
    [[sns]]
      url = 'write.as'
      icon = 'writefreely.png'
    [[sns]]
      url = 'x.com'
      icon = 'x.svg'
    [[sns]]
      url = 'youtube.com'
      icon = 'youtube.svg'
  ##### END: syndication #####
### END: Hugo module settings ###

### BGN: Other Settings ###
  [analytics]
    enable = true
    position = 'head'       # head or body
    cfwebanalytics = '07a05e5302d1458da3561ce41791e284'       # https://cloudflare.com | 'privacy-first'
    counterdev = 'youronlyone'           # https://counter.dev | 'privacy-friendly'
    #microanalyticsio = 'ZwSg9rf6GA'     # https://microanalytics.io | 'privacy-first', 'green energy'
    #microsoftclarity = '63ddi0b99e'     # https://clarity.microsoft.com
    naver = '1375cb4224f1c40'                # https://analytics.naver.com for youronly.one
    #naver = '137a7c92882ac90'                # https://analytics.naver.com for im.youronly.one
    swetrix = 'bYdcXUajNvru'              # https://swetrix.com | 'privacy-first'

  [geotags]
    enable = true
    placename = 'Manila'
    poslat = '14.599781'
    poslong = '120.973935'
    region = 'PH-00'

  [indieweb]
    enable = true
    indieauth = 'https://indieauth.com/auth'
    pingback = 'https://webmention.io/im.youronly.one/xmlrpc'
    webmention = 'https://webmention.io/im.youronly.one/webmention'

    # Usually: 'https://pubsubhubbub.appspot.com/', 'https://examplecom.superfeedr.com/', 'https://pubsubhubbub.superfeedr.com/', 'https://websubhub.com/hub'
    websubhubs = ['https://pubsubhubbub.appspot.com/', 'https://youronlyone.superfeedr.com/', 'https://pubsubhubbub.superfeedr.com/', 'https://websubhub.com/hub']

    [openid]
      delegate = 'https://im.youronly.one/'
      server = 'https://openid.indieauth.com/openid'

  [mathml]
    position = 'head'
    src = 'https://cdn.jsdelivr.net/npm/mathjax@latest/es5/tex-mml-chtml.min.js'

  [social]
    # See: https://github.com/gohugoio/hugo/pull/12234
    enable = true
    #facebook_authorid = ''                         # template-only
    ##codeberg = 'techmagus'                                   # username
    #codepen = ''                                    # username
    #deviantart = 'laibcoms'                                 # URL-name without @
    #email = 'contact@im.youronly.one'                                      # address@example.com
    facebook = 'YourOnly.ONE.ofcl'                                   # URL-name
    facebook_admin = '532996690,100042645428366,2308171266072912'                             # profile ID number and page admin to get domain insights
    facebook_appid = '183794425326191'                             # app ID
    facebook_authorid = '2308171266072912'                          # user ID
    facebook_pageid = '339301830572387'                            # page ID
    github = 'techmagus'                                     # username
    gitlab = 'techmagus'                                     # username
    #googlescholar = ''                              # username
    #instagram = 'youronly.one.ofcl'                                  # username
    keybase = 'yukino'                                    # username
    ##keyoxide = 'youronly.one/?verify=keyoxide'                                   # URL
    #linkedin = 'youronlyone'                                   # URL-name
    mastodon = 'c.im/@youronlyone'                                   # example.com/@username
    #medium = 'youronly.one'                                     # username without @
    #pinterest = 'YourOnlyONEofcl'                                  # username
    pixelfed = 'pixelfed.social/@youronlyone'                                   # example.com/@username
    #reddit = 'Laibcoms'                                     # username
    #researchgate = ''                               # username
    #slideshare = ''                                 # username
    #stackoverflow = '306674'                              # user number
    #strava = 'faithfulathlete'                                     # URL-name or userID number
    #telegram = ''                                   # URL-name
    ##threads = 'youronly.one.ofcl'                                    # username without @
    tumblr = 't.youronly.one'                                     # URL
    twitter = 'YourOnlyONEofcl'                                    # username; do not include @-at
    twitter_creator = '@YourOnlyONEofcl'                            # @username
    twitter_site = '@YourOnlyONEofcl'                               # @username
    wordpress = 'youronlyoneofcl.wordpress.com'                                  # URL
    youtube = 'YourOnlyONEofcl'                                    # username without @

  [taxonomy]
    categories = true
    tags = true

  [toc]
    level_start = 1
    level_end = 6
    list_element = 'ol'
    list_class = 'upper-latin'

  [verifications]
    enable = true
    flattr = '4j1gl5'
    followit = 'uYZyV7MVARnWg9phNgMQ'
    #google = ''
    #microsoft = ''
    naver = '0212955cb24d6e2c67f92be3c7833cae8a98fa8e'
    ocs = 'c563648adcfa021a0dfd3d3d8f0be64a'
    #pinterest = ''
    wot = '06c7ef6e7986586661ef'
    #yandex = ''

  ##### BGN: webfonts #####
    [[webfonts]]
      enable = true
      url = 'https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap'
    [[webfonts]]
      enable = true
      url = 'https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&display=swap'
    [[webfonts]]
      enable = true
      url = 'https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;700&display=swap'
    [[webfonts]]
      enable = true
      url = 'https://fonts.googleapis.com/css2?family=Noto+Sans+Phoenician&family=Noto+Sans+Hebrew:wght@400;700&display=swap'
    [[webfonts]]
      enable = true
      url = 'https://fonts.googleapis.com/css2?family=Noto+Sans+Tagalog&family=Noto+Sans+Tagbanwa&family=Noto+Sans+Buhid&family=Noto+Sans+Hanunoo&display=swap'
    [[webfonts]]
      enable = true
      url = 'https://fonts.googleapis.com/css2?family=Noto+Sans+Mono:wght@400;700&display=swap'
    [[webfonts]]
      enable = true
      url = 'https://fonts.googleapis.com/css2?family=Noto+Color+Emoji&display=swap'
    #[[webfonts]]
    #  enable = true
    #  url = 'https://fonts.googleapis.com/css2?family=Bungee+Spice&display=swap'
    #[[webfonts]]
    #  enable = true
    #  url = 'https://fonts.googleapis.com/css2?family=Honk&display=swap'
  ##### END: webfonts #####

  [semweb]
    datecreated = "2017-01-01"
    isblog = true

  #  org = "yelosan"

  #  #isni = ""
  #  #issn = ""
  #  acquirelicensepage = "https://im.youronly.one/p/legal-notice/"
  #  copyrightnotice = "Copyleft 🄯 CC-BY-SA 4.0 International by JC John Sese Cuneta"
  #  credittext = "I'M YourOnly.One (https://im.youronly.one/)"
  #  datecreated = "2003-12-12"
  #  isblog = true
  #  license = "https://im.youronly.one/p/legal-notice/"
  #  publisher = "https://yelosan.youronly.one/"
  #  sameas = [
  #    "https://facebook.com/101597304949708/",
  #    "https://facebook.com/yelosanpub/",
  #    "https://c.im/@youronlyone",
  #    "https://mastodon.social/@youronlyone",
  #    "https://mastodon.online/@youronlyone",
  #    "https://pixelfed.social/youronlyone",
  #    "https://youtube.com/YourOnlyONEofcl",
  #    "https://twitter.com/YourOnlyONEofcl",
  #    "https://instagram.com/YourOnly.One",
  #    "https://facebook.com/YourOnly.ONE.ofcl",
  #    "https://www.pinterest.com/YourOnlyONEofcl",
  #    "https://www.eyeem.com/u/YourOnlyOne",
  #    "https://www.goodreads.com/youronlyone",
  #    "https://vero.co/youronlyone",
  #    "https://ecency.com/@youronlyone",
  #    "https://hive.blog/@youronlyone",
  #    "https://steemit.com/@youronlyone",
  #    "https://gitlab.com/techmagus",
  #    "https://github.com/techmagus"
  #  ]

  #  [[semweb.persons]]
  #    person = "yuki"
  #    #id = ""
  #    #name = ""ᜌᜓᜃᜒ (雪亮 | 스노 | Yuki)"
  #    #url = ""
  #    #avatar = ""
  #    #rel = "noopener external nofollow"
### END: Other Settings ###
