# See: https://gohugo.io/about/hugo-and-gdpr/
# See: https://gohugo.io/methods/site/config/#privacy

[disqus]
  disable = false

[googleAnalytics]
  anonymizeIP = true
  disable = true
  respectDoNotTrack = true
  useSessionStorage = true

[instagram]
  disable = true
  simple = true

[twitter]
  disable = true
  enableDNT = true
  simple = true

[vimeo]
  disable = false
  enableDNT = true
  simple = true

[youTube]
  disable = false
  privacyEnhanced = true
