# See: https://gohugo.io/content-management/related/#configure-related-content

includeNewer = true                       # "include pages newer than the current page"
threshold = 80
toLower = true                            # default: false; "lowercase keywords in both the indexes and the queries"

#[[indices]]
#  applyFilter = false                     # currently only used for 'fragments' as of v0.111.x)
#  cardinalityThreshold = 0                # default: 0; used to remove common keywords from the index
#  name = "name"
#  pattern = "2006"                        # default: 2006; or 200601 (year and month); only for dates
#  toLower = true                          # same as the global option above
#  type = "basic"                          # 'basic' or 'fragments'
#  weight =


#[[indices]]
#  name = "fragmentrefs"
#  type = "fragments"
#  applyFilter = false
#  weight = 60
#  cardinalityThreshold = 50

## Useful in hub/aggregate blogs
[[indices]]
  applyFilter = false
  cardinalityThreshold = 0
  name = "channels"
  pattern = ""
  toLower = false
  type = "basic"
  weight = 90

[[indices]]
  applyFilter = false
  cardinalityThreshold = 0
  name = "categories"
  pattern = ""
  toLower = false
  type = "basic"
  weight = 90

[[indices]]
  applyFilter = false
  cardinalityThreshold = 0
  name = "date"
  pattern = ""
  toLower = false
  type = "basic"
  weight = 10

[[indices]]
  applyFilter = false
  cardinalityThreshold = 0
  name = "keywords"
  pattern = ""
  toLower = false
  type = "basic"
  weight = 70

[[indices]]
  applyFilter = false
  cardinalityThreshold = 0
  name = "lastmod"
  pattern = ""
  toLower = false
  type = "basic"
  weight = 80

[[indices]]
  applyFilter = false
  cardinalityThreshold = 0
  name = "series"
  pattern = ""
  toLower = false
  type = "basic"
  weight = 100

[[indices]]
  applyFilter = false
  cardinalityThreshold = 0
  name = "tags"
  pattern = ""
  toLower = false
  type = "basic"
  weight = 100
